### ISSUE TITLE
vue & form & undefined is required 

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#140]
# vue & form & undefined is required 

undefined is required

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/112147424-ab3d7480-8c17-11eb-89a7-5cc13c0f9bc8.png)


![image](https://user-images.githubusercontent.com/7291672/112147486-b7c1cd00-8c17-11eb-999b-10f02b96f297.png)

**Comment by xgqfrms** [comment]
element ui form & undefined is required

**Comment by xgqfrms** [comment]
https://blog.csdn.net/HermitSun/article/details/105601317

<el-form-item>上的prop名称不对，应当与rules中的名称一致；
绑定的属性没有在data中声明；
没有在<el-form>上指定model。

**Comment by xgqfrms** [comment]
# element-ui form 表单验证

https://element.eleme.io/#/zh-CN/component/form#biao-dan-yan-zheng


https://codepen.io/xgqfrms/pen/KKawVQv

**Comment by xgqfrms** [comment]
https://segmentfault.com/q/1010000019262990

https://blog.csdn.net/shulan5/article/details/103810317

https://www.jianshu.com/p/dd625ba4ea52

**Comment by xgqfrms** [comment]
prop对应的不单单是rules规则里面的验证项，同时对应着form-item下的v-model的值。

prop绑定的类要与el-form-item下的v-model的值相对应。

**Comment by xgqfrms** [comment]
？？？WTF

**Comment by xgqfrms** [comment]
# css star ⭐️

```css


<style lang="scss" scoped>
    [data-required="star"] {
        position: relative;
    }
    [data-required="star"]::before {
        position: absolute;
        content: '*';
        color: #F56C6C;
        margin-right: 4px;
        top: 33%;
        left: 45px;
}
</style>

```
