### ISSUE TITLE
vue scoped & import css file

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#186]
# vue scoped & import css file

```vue
<style lang="scss" scoped src="./styles/vertical-video-9vs16-container.scss"></style>

<style lang="scss" scoped src="./styles/text-warning.scss"></style>
<style lang="scss" scoped src="./styles/creative-add-group-container.scss"></style>
<style lang="scss" scoped src="./styles/text-add-group-container.scss"></style>
<style lang="scss" scoped src="./styles/form-item-question-tooltip.scss"></style>
```

**Comment by xgqfrms** [comment]
`form-item-question-tooltip.scss`


```scss

.gdt-creative-title-question-item {
    box-sizing: border-box;
    /deep/ .el-form-item__label {
        transform: translateX(-20px);
    }
    // /deep/ .el-form-item__content {
    //     margin-left: 130px !important;
    // }
    .icon-question-circle {
        box-sizing: border-box;
        position: absolute;
        left: -26px;
        top: 9px;
        cursor: pointer;
        color: #909399;
        opacity: 0.99;
    }
}

```
