### ISSUE TITLE
overwrite element-ui style

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#189]
# overwrite element-ui style

```vue
.create-ad-filter {
    .new-custom-select-bg {
        /deep/ .el-input.is-disabled {
            .el-input__inner {
                background-color: transparent !important;
            }
        }
    }
}

</style>

```

```vue

<style lang="scss">

.create-ad-filter {
    .new-custom-select-bg {
        .el-input.is-disabled {
            .el-input__inner {
                background-color: transparent !important;
            }
        }
    }
}

</style>


```

**Comment by xgqfrms** [comment]
```css
.create-ad-filter .new-custom-select-bg[data-v-ab7224d2] .el-input.is-disabled .el-input__inner {
    background-color: transparent !important;
}

```
