### ISSUE TITLE
element-ui & codepen & vue cdn bug

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#216]
# element-ui & codepen & vue cdn bug

https://github.com/ElemeFE/element/issues/21686

https://codepen.io/xgqfrms/pen/PoOmpjN?editors=1111

```html
<!-- <script src="https://unpkg.com/vue/dist/vue.js"></script> -->
<!-- <script src="https://cdn.xgqfrms.xyz/vue/2.1.8/vue.min.js"></script> -->
<!-- https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.8/vue.js -->

<script src="https://unpkg.com/vue@2.6.10/dist/vue.js"></script>

<script src="https://unpkg.com/element-ui@2.15.7/lib/index.js"></script>

```

**Comment by xgqfrms** [comment]
# css important not work ??? webpack 打包顺序 bug ???

```html

<style lang="scss">

.icon-question-circle-dark {
    background: #000 !important;
    color: #fff !important;
}

// css important not work ??? webpack 打包顺序 bug

.icon-question-circle-dark[x-placement^=bottom] .popper__arrow::after {
    border-bottom-color: #000 !important;
}
.icon-question-circle-dark[x-placement^=top] .popper__arrow::after {
    border-bottom-color: #000 !important;
}

</style>


```

![image](https://user-images.githubusercontent.com/7291672/153838067-4921f578-d791-46cb-84b9-e0812983f87e.png)

**Comment by xgqfrms** [comment]
# TMD 

> holy shit


![image](https://user-images.githubusercontent.com/7291672/153838930-9d95e097-2f93-4089-8a1c-941376f8dbdb.png)


```scss


.icon-question-circle-dark {
    background: #000 !important;
    color: #fff !important;
}

// css important not work ??? webpack 打包顺序 bug

.icon-question-circle-dark[x-placement^="bottom"] .popper__arrow::after {
    border-bottom-color: #000 !important;
}

.icon-question-circle-dark[x-placement^="top"] .popper__arrow::after {
    border-bottom-color: #000 !important;
}


.icon-question-circle-dark .popper__arrow::after {
-   border-bottom-color:#303133 !important;
+   border-top-color:#303133 !important;
}

```

**Comment by xgqfrms** [comment]
https://www.cnblogs.com/xgqfrms/p/15802812.html

**Comment by xgqfrms** [comment]
# ::v-deep not work

```js
<style lang="scss" scoped>

// body ::v-deep {
//     .icon-question-circle-dark {
//         background: #000 !important;
//         color: #fff !important;
//     }
//     .icon-question-circle-dark[x-placement^=bottom] .popper__arrow::after {
//         border-bottom-color: #000 !important;
//     }
//     .icon-question-circle-dark[x-placement^=top] .popper__arrow::after {
//         border-bottom-color: #000 !important;
//     }
// }


</style>

```

**Comment by xgqfrms** [comment]
```html

<style lang="scss" src="./custom-popover.scss"></style>


```

```scss
.custom-question-class {
    min-width: 30px !important;
    width: auto !important;
}

.custom-popover-class {
    min-width: 30px !important;
    width: auto !important;
    font-size: 12px !important;
    color: #FFFFFF !important;
    background: #303133 !important;
}
.custom-popover-class {
    .popper__arrow::after {
        border-top-color:#303133 !important;
    }
}

```
