### ISSUE TITLE
vue & 组件化应用构建

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#37]
# vue & 组件化应用构建

https://scrimba.com/p/pXKqta/cEQVkA3

https://cn.vuejs.org/v2/guide/#%E7%BB%84%E4%BB%B6%E5%8C%96%E5%BA%94%E7%94%A8%E6%9E%84%E5%BB%BA

https://cn.vuejs.org/v2/guide/components.html

https://cn.vuejs.org/v2/guide/single-file-components.html

**Comment by xgqfrms** [comment]
# antd-RangePicker-datepicker

> placeholder 

placeholder | 非范围选择时的占位内容 | string | — 
-- | -- | -- | -- 
 placeholder | placeholder of date input | string\|RangePicker[]


https://ant.design/components/date-picker/

https://codesandbox.io/s/92yzp7028o

# element date-picker

https://element.eleme.io/#/zh-CN/component/date-picker

![image](https://user-images.githubusercontent.com/7291672/50500571-38bba980-0a8d-11e9-8c7f-76b228464081.png)


placeholder | 非范围选择时的占位内容 | string | — | —
-- | -- | -- | -- | --
start-placeholder | 范围选择时开始日期的占位内容 | string | — | —
end-placeholder | 范围选择时结束日期的占位内容 | string | — | —

**Comment by xgqfrms** [comment]
# vue & style scoped

https://vue-loader.vuejs.org/guide/scoped-css.html

**Comment by xgqfrms** [comment]
# vue shorthands

> `:` & `@`


https://vuejs.org/v2/guide/syntax.html#Shorthands

![](https://img2018.cnblogs.com/blog/740516/201812/740516-20181228131725523-711191574.png)


## v-for


https://vuejs.org/v2/guide/list.html

![](https://img2018.cnblogs.com/blog/740516/201812/740516-20181228131920748-1881152343.png)

**Comment by xgqfrms** [comment]
# vue & scss

https://github.com/vuejs/vue-loader/issues/363
https://vue-loader.vuejs.org/guide/pre-processors.html#sass

![image](https://user-images.githubusercontent.com/7291672/50504208-f737f800-0aa6-11e9-8b83-4b6a7cff8445.png)

**Comment by xgqfrms** [comment]
https://vue-loader.vuejs.org/guide/pre-processors.html#sass

> `sass-loader` for `scss`

![image](https://user-images.githubusercontent.com/7291672/50504546-42530a80-0aa9-11e9-9f82-bd315826a3ab.png)

![image](https://user-images.githubusercontent.com/7291672/50504563-6282c980-0aa9-11e9-904c-aae313660438.png)

**Comment by xgqfrms** [comment]
# sass playground

https://sass.js.org/

https://codepen.io/webgeeker/pen/NeaKjm

```scss

    /* scss variables */
    $default-color: #000;
    .audit-commmon-lable{
        color: $default-color;
        &::after{
            display: block;
            content: ":";
        }
    }
    /*
    .audit-commmon-lable::after{
        display: inline-block;
        content: ":";
    }
    */

```
