### ISSUE TITLE
mint-ui & index-list

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#65]
# mint-ui & index-list

https://mint-ui.github.io/docs/#/en2/index-list

https://mint-ui.github.io/docs/#/zh-cn2/index-list

https://github.com/mint-ui/docs/blob/master/src/pages/zh-cn/index-list.md

> demo

https://elemefe.github.io/mint-ui/#/index-list

**Comment by xgqfrms** [comment]
https://www.cnblogs.com/xgqfrms/p/11132935.html

**Comment by xgqfrms** [comment]
```js
    autoShowActived() {
        let list = document.querySelector(`.mint-indexlist-navlist`);
        let onceFlag = list.dataset.onceFlag || false;
        if (!onceFlag) {
            list.dataset.onceFlag = true;
            list.addEventListener(`click`, function(e) {
                let items = document.querySelectorAll(`.mint-indexlist-navitem`);
                items.forEach(item => item.classList.remove(`mint-indexlist-navitem-actived`));
                if (list.firstElementChild !== e.target) {
                    e.target.classList.add(`mint-indexlist-navitem-actived`);
                }
            });
        } else {
            log(`only need bind once!`);
        }
    },
```

```css

/* overwrite css */
.mint-indexlist-navitem{
    font-size: 0.22rem;
    color: rgba(136,136,136,1);
    line-height: 0.44rem;
    width: 0.44rem;
    height: 0.44rem;
}

.mint-indexlist-navitem-actived{
    background:rgba(26,144,255,1);
    border-radius: 50%;
    text-align: center;
    vertical-align: middle;
    color: #fff;
}

```
