### ISSUE TITLE
element ui & input number bug

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/vue#78]
# element ui & input number bug

**Comment by xgqfrms** [comment]
https://stackoverflow.com/questions/57568453/vue-element-ui-get-index-of-table-row/59478609#59478609

**Comment by xgqfrms** [comment]
```css

<style lang="css">
  /* global css */
  .auto-clearfix::after{
    display: table;
    overflow: hidden;
    visibility: hidden;
    width: 0;
    height: 0;
    clear: both;
    content: "";
  }
</style>

```
